### ISSUE TITLE
homework1----Huanwen Wu

### ISSUE THREAD

**Issue by huanwenwu** [huanwenwu/stat679work#1]
Hi Professor, I'm Huanwen Wu, and  this is my solution for homework1, Thanks! @ Cécile Ané

**Comment by huanwenwu** [comment]
Hi Professor, here is my last commit for homework 1:
https://github.com/huanwenwu/stat679work/commit/5fbc315487c83f74161c0a215fc8c3283a974bbe
@cecileane

**Comment by cecileane** [comment]
Hi Huanwen,

Thanks for tagging me! I had not received any email when you first opened the issue, but I did receive it after you tagged me. Thank you.

Your scripts ran just fine. Below is some feedback that might be helpful for future homework.

In your code, please use indentation to make your code more human-readable. Blocks of code inside a `do`/`done` block should be indented, in particular. Unless the block is ultra short, it is also best to put the code on a new line, that is, go to a new line after `do` (unlike what you did in both of your scripts). The same rules should be followed for any language, not just the shell.

You documentation of the project is rather minimal (i.e. your `readme` file does not say much to help the reader reproduce your analysis). But you do have helpful comments inside your code.

You learned about parameter substitution, and you have a clever use of cut with various delimiters, great job! Unfortunately, you did not get much practice with `grep` as a result, and you did not use any _extended_ regular expressions. It was one of the main goals of this homework. Learning to use extended regular expressions would be useful for all other languages, not just the shell. For this reason, please use `grep`, `sed` and extended regexp instead of parameter substitution in the next homework.

I like that your summary script writes to the standard output. You should document this behavior somewhere, and you should write in your readme file how you used your script to produce the summary file: with a command that redirects the output.

Your output file is not in csv format: spaces are used to separate the columns. To use the csv format (comma-separated variables), you would need to delete the spaces and replaced them by commas.

Please close this issue, or [assign](https://help.github.com/articles/assigning-issues-and-pull-requests-to-other-github-users/) it to me and I can close it.

**Comment by cecileane** [comment]
Hi Huanwen, could you please close this issue?

**Comment by huanwenwu** [comment]
Sure. Thanks, Professor~@cecileane
