### ISSUE TITLE
Homework1--exercise3

### ISSUE THREAD

**Issue by huanwenwu** [huanwenwu/stat679work#2]
Hi Professor, it is my commit for homework 1--excercise 3. Thanks~  @cecileane

https://github.com/huanwenwu/stat679work/commit/5fbc315487c83f74161c0a215fc8c3283a974bbe

**Comment by cecileane** [comment]
Thanks Huanwen! This is my way of asking Lan (@lan) and Youjia (@zhou325) to try your script and provide feedback on it.

**Comment by lan** [comment]
Hello Huanwen,

Your code is successfully run in my computer.  And I like your comments about the extended regular expression, which are very clear and understandable. I learnt a lot about how to comment my code from you.

There is my suggestion about the files organization: when there are too many files, maybe it is better to use different subdirectories to contain them. Because at the first time, after I ran your code, I didn't find the result file. 

Overall, I think you did very well.

**Comment by zhou325** [comment]
Hi Huanwen,

Nice work! I ran your script successfully in my computer!  In this exercise, you mainly use `grep` and `sed` to search and replace components, and you also use a `for` loop , an `if` statement and `basename`, which fully meets professor's requirement.  I like the way you name your variables, because it does help me to understand what the value of this variable is likely to be at the first glance, and I realize that this is what I need to improve in my own script.  I also like the way you comment on your code, which explain your commands clearly and is very helpful for me to understand your code.  In your `readme` file, you explain what is in the directory and give instructions on how to run your code, which helps me run your code successfully.

Here are some suggestions:
Firstly, when I run your code and get the table, I find that the value of `Nruns` is missing for analysis `net1_snaq`.  I think this might because that in your code, you search the number of runs by `grep "FINISHED SNaQ for run" $filename`, however, in the file `net1_snaq.log`, there isn't such a sentence but only `FINISH SNaQ`.  To get `Nruns` for every analysis successfully, I think you can try the following code: `grep -Eo "BEGIN: \d+ runs" $filename`
Besides, when I run your script for more than one time, it keeps appending new lines to the existing file.  So the resulting file contains the same information for several times.  To create a new table for every run, you can try to replace the code `echo "analysis","h","CPUtime","Nruns","Nfail","fabs","frel","xabs","xrel","seed","under3460","under3450","under3440" >> hw1.csv` 
with `echo "analysis","h","CPUtime","Nruns","Nfail","fabs","frel","xabs","xrel","seed","under3460","under3450","under3440" > hw1.csv`

In general, you did a great work in this homework, and I also learned a lot from your work.
Thank you very much!

Youjia
