### ISSUE TITLE
hw2--merged file

### ISSUE THREAD

**Issue by huanwenwu** [huanwenwu/stat679work#3]
Hi professor, this is my solution of hw2, thanks!  @cecileane

----Huanwen Wu

**Comment by cecileane** [comment]
Hi Huanwen,

Nice job! More details below.

## overall presentation

In general, it's good to get into the habit of separating the scripts and input/output files into different directories.

Your instructions didn't work straight "out of the box" because your readme file said this: `python merge_script.py` but your script name had a small typo: `merge_scrip.py` (not t). It would have been great if your readme file had said something about assumptions made by your script, and something about where its output would go.

## running your script

Your script worked just fine, the output was great.

Unfortunately, your script did not take any argument. In fact, it ignored any argument that I tried to give it. It would have been great if you had used the argparse module, and if your script had read input data files from arguments. As it is, your script cannot be used for future month's data: unless the user changes the names of the input file, and also changes the name of the output file after it's been created. That's not very user-friendly. At the very least, your readme file should tell the user about this limitations with data files.

## about your code

The good thing is that you hard-coded the file names in one single place, so if the user wanted to change the file names inside the script, it would be fairly easy. There also is a single place to change, if you wanted to read these file names from the script arguments.

Your code does not have a single function. It is best practice to break the problem down into several functions: it helps make the code human-readable, re-usable, you can document functions with docstrings, you can test them one at a time, check that further development don't break previous code (if you have a test for each function), etc.

You could definitely put more comments in your code, to explain more.

It's great that you checked that the dates are ordered in the energy data. However, your error message is not very informative: (what is not ordered? in which file?)

```python
print ("Not Ordered!")
exit()
```

and you should exit with an Exception, so that the script exits with a bad exit status, like this for instance:

```python
raise Exception("the date are not ordered in your energy file!")
```

Some of your variables are also poorly named. For example, `data_time` could be made a lot more explicit. `data` is usually not helpful. Here, `energy_time` would have made your code more human-readable. You had to use `data_time_t` for the temparature data, but "t" is easily misunderstood for many things: like time (not temperature). So `temp_time` or `temparature_time` would have been a better choice than `data_time_t`.

When you check the ordering of the dates in the temperature file, you have this on line 50:

```python
if data_time_t[i] <= data_time_t[i+1] or data_time_t[i][9:11]=="12":
```

This check is incorrect for times in the day near noon or midnight: un-ordered days will incorrectly pass the tests if the first is near 12am or 12pm.

You also hard-coded the first line, which is a rather useless header (it does not say what the columns have):

```python
f.write("Plot Title: 10679014 jackson July29\n")
```

A better choice would have been to *not* write this, or to read the first line in the temperature file, and write it. That way, if future files have a different first line, the output file would match it.

You can go ahead and close this issue now. Thanks!
